name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: print versions
      run: make --version; gcc --version
    - name: run-tests
      run: make run-tests
    - name: mnist main train
      run: build/mnist-main train
            --epochs 1
            --images data/mnist/t10k-images-idx3-ubyte
            --labels data/mnist/t10k-labels-idx1-ubyte
            --out mnist-reseau.bin
